version: '3.8'

services:
  narratix:
    image: ${DOCKER_IMAGE_URL}
    container_name: narratix-container
    restart: always # 컨테이너 종료시 컨테이너를 자동으로 띄움
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod